openapi: 3.2.0
info:
  title: Akash Network Console Chain API
  description: API providing data to the Akash Network Console
  version: v1
servers:
- url: https://console-api-sandbox.akash.network
tags:
- name: Chain
paths:
  /v1/blockchain-status:
    get:
      summary: Get blockchain reachability status
      tags:
      - Chain
      security: []
      responses:
        '200':
          description: Returns blockchain reachability status
          content:
            application/json:
              schema:
                type: object
                properties:
                  isBlockchainReachable:
                    type: boolean
                required:
                - isBlockchainReachable
      operationId: getV1BlockchainStatus
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT token for authenticated users, sent in "Authorization: Bearer %token" header.'
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for programmatic access.
    x-user-id:
      type: apiKey
      in: header
      name: x-user-id
    x-owner-address:
      type: apiKey
      in: header
      name: x-owner-address
