openapi: 3.2.0
info:
  title: Akash Network Console Certificate API
  description: API providing data to the Akash Network Console
  version: v1
servers:
- url: https://console-api-sandbox.akash.network
tags:
- name: Certificate
paths:
  /v1/certificates:
    post:
      summary: Create certificate
      tags:
      - Certificate
      security:
      - BearerAuth: []
      - ApiKeyAuth: []
      responses:
        '400':
          description: This endpoint has been removed. mTLS certificates are no longer required as identity is now verified via API key.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      operationId: postV1Certificates
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT token for authenticated users, sent in "Authorization: Bearer %token" header.'
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for programmatic access.
    x-user-id:
      type: apiKey
      in: header
      name: x-user-id
    x-owner-address:
      type: apiKey
      in: header
      name: x-owner-address
