openapi: 3.2.0
info:
  title: AKASH - gRPC Gateway docs Mint API
  description: A REST interface for state queries
  version: 1.0.0
tags:
- name: Mint
paths:
  /minting/parameters:
    get:
      deprecated: true
      summary: Minting module parameters
      tags:
      - Mint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  mint_denom:
                    type: string
                  inflation_rate_change:
                    type: string
                  inflation_max:
                    type: string
                  inflation_min:
                    type: string
                  goal_bonded:
                    type: string
                  blocks_per_year:
                    type: string
        '500':
          description: Internal Server Error
      operationId: getMintingParameters
      x-operation-id-source: derived
  /minting/inflation:
    get:
      deprecated: true
      summary: Current minting inflation value
      tags:
      - Mint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal Server Error
      operationId: getMintingInflation
      x-operation-id-source: derived
  /minting/annual-provisions:
    get:
      deprecated: true
      summary: Current minting annual provisions value
      tags:
      - Mint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal Server Error
      operationId: getMintingAnnualProvisions
      x-operation-id-source: derived
components:
  securitySchemes:
    kms:
      type: http
      scheme: basic
