swagger: '2.0'
info:
  title: AKASH - gRPC Gateway docs Addresses Gaia REST API
  description: A REST interface for state queries
  version: 1.0.0
tags:
- name: Gaia REST
paths:
  /node_info:
    get:
      description: Information about the connected node
      summary: The properties of the connected node
      tags:
      - Gaia REST
      produces:
      - application/json
      responses:
        '200':
          description: Node status
          schema:
            type: object
            properties:
              application_version:
                properties:
                  build_tags:
                    type: string
                  client_name:
                    type: string
                  commit:
                    type: string
                  go:
                    type: string
                  name:
                    type: string
                  server_name:
                    type: string
                  version:
                    type: string
              node_info:
                properties:
                  id:
                    type: string
                  moniker:
                    type: string
                    example: validator-name
                  protocol_version:
                    properties:
                      p2p:
                        type: string
                        example: 7
                      block:
                        type: string
                        example: 10
                      app:
                        type: string
                        example: 0
                  network:
                    type: string
                    example: gaia-2
                  channels:
                    type: string
                  listen_addr:
                    type: string
                    example: 192.168.56.1:26656
                  version:
                    description: Tendermint version
                    type: string
                    example: 0.15.0
                  other:
                    description: more information on versions
                    type: object
                    properties:
                      tx_index:
                        type: string
                        example: 'on'
                      rpc_address:
                        type: string
                        example: tcp://0.0.0.0:26657
        '500':
          description: Failed to query node status
securityDefinitions:
  kms:
    type: basic
