openapi: 3.2.0
info:
  title: AKASH - gRPC Gateway docs Bank API
  description: A REST interface for state queries
  version: 1.0.0
tags:
- name: Bank
paths:
  /bank/balances/{address}:
    get:
      deprecated: true
      summary: Get the account balances
      tags:
      - Bank
      parameters:
      - in: path
        name: address
        description: Account address in bech32 format
        required: true
        x-example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
        schema:
          type: string
      responses:
        '200':
          description: Account balances
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                      example: stake
                    amount:
                      type: string
                      example: '50'
        '500':
          description: Server internal error
      operationId: getBankBalancesByAddress
      x-operation-id-source: derived
  /bank/accounts/{address}/transfers:
    post:
      deprecated: true
      summary: Send coins from one account to another
      tags:
      - Bank
      parameters:
      - in: path
        name: address
        description: Account address in bech32 format
        required: true
        x-example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
        schema:
          type: string
      responses:
        '202':
          description: Tx was succesfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: array
                    items:
                      type: string
                  fee:
                    type: object
                    properties:
                      gas:
                        type: string
                      amount:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                              example: stake
                            amount:
                              type: string
                              example: '50'
                  memo:
                    type: string
                  signature:
                    type: object
                    properties:
                      signature:
                        type: string
                        example: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
                      pub_key:
                        type: object
                        properties:
                          type:
                            type: string
                            example: tendermint/PubKeySecp256k1
                          value:
                            type: string
                            example: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
                      account_number:
                        type: string
                        example: '0'
                      sequence:
                        type: string
                        example: '0'
        '400':
          description: Invalid request
        '500':
          description: Server internal error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                base_req:
                  type: object
                  properties:
                    from:
                      type: string
                      example: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
                      description: Sender address or Keybase name to generate a transaction
                    memo:
                      type: string
                      example: Sent via Cosmos Voyager 🚀
                    chain_id:
                      type: string
                      example: Cosmos-Hub
                    account_number:
                      type: string
                      example: '0'
                    sequence:
                      type: string
                      example: '1'
                    gas:
                      type: string
                      example: '200000'
                    gas_adjustment:
                      type: string
                      example: '1.2'
                    fees:
                      type: array
                      items:
                        type: object
                        properties:
                          denom:
                            type: string
                            example: stake
                          amount:
                            type: string
                            example: '50'
                    simulate:
                      type: boolean
                      example: false
                      description: Estimate gas for a transaction (cannot be used in conjunction with generate_only)
                amount:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                        example: stake
                      amount:
                        type: string
                        example: '50'
        description: The sender and tx information
        required: true
      operationId: postBankAccountsByAddressTransfers
      x-operation-id-source: derived
  /bank/total:
    get:
      deprecated: true
      summary: Total supply of coins in the chain
      tags:
      - Bank
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                          example: stake
                        amount:
                          type: string
                          example: '50'
        '500':
          description: Internal Server Error
      operationId: getBankTotal
      x-operation-id-source: derived
  /bank/total/{denomination}:
    parameters:
    - in: path
      name: denomination
      description: Coin denomination
      required: true
      x-example: uatom
      schema:
        type: string
    get:
      deprecated: true
      summary: Total supply of a single coin denomination
      tags:
      - Bank
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid coin denomination
        '500':
          description: Internal Server Error
      operationId: getBankTotalByDenomination
      x-operation-id-source: derived
components:
  securitySchemes:
    kms:
      type: http
      scheme: basic
