swagger: '2.0'
info:
  title: AKASH - gRPC Gateway docs Addresses Auth API
  description: A REST interface for state queries
  version: 1.0.0
tags:
- name: Auth
paths:
  /auth/accounts/{address}:
    get:
      deprecated: true
      summary: Get the account information on blockchain
      tags:
      - Auth
      produces:
      - application/json
      parameters:
      - in: path
        name: address
        description: Account address
        required: true
        type: string
        x-example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
      responses:
        '200':
          description: Account information on the blockchain
          schema:
            type: object
            properties:
              type:
                type: string
              value:
                type: object
                properties:
                  account_number:
                    type: string
                  address:
                    type: string
                  coins:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                          example: stake
                        amount:
                          type: string
                          example: '50'
                  public_key:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: string
                  sequence:
                    type: string
        '500':
          description: Server internel error
  /v1/auth/signup:
    post:
      summary: Creates a new user without sending a verification email
      tags:
      - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
              required:
              - email
              - password
      responses:
        '204':
          description: User created successfully
securityDefinitions:
  kms:
    type: basic
